// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyAZjvzm9HE28bKZzYRxb4b7jXtPaHd1k',
    appId: '1:213904310776:web:2fe6fbfcb9e3f58670960d',
    messagingSenderId: '213904310776',
    projectId: 'mws-kel-8',
    authDomain: 'mws-kel-8.firebaseapp.com',
    storageBucket: 'mws-kel-8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1KCNjL1nhjW_PbIbaqDm1i9vLZ8hfZX0',
    appId: '1:213904310776:android:98a99f227146bf0570960d',
    messagingSenderId: '213904310776',
    projectId: 'mws-kel-8',
    storageBucket: 'mws-kel-8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvZpTW6c40lGGsRzGXLNBQ9KU9rwHhtfU',
    appId: '1:213904310776:ios:f973283690a1748570960d',
    messagingSenderId: '213904310776',
    projectId: 'mws-kel-8',
    storageBucket: 'mws-kel-8.firebasestorage.app',
    iosBundleId: 'com.example.lensamartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvZpTW6c40lGGsRzGXLNBQ9KU9rwHhtfU',
    appId: '1:213904310776:ios:f973283690a1748570960d',
    messagingSenderId: '213904310776',
    projectId: 'mws-kel-8',
    storageBucket: 'mws-kel-8.firebasestorage.app',
    iosBundleId: 'com.example.lensamartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyAZjvzm9HE28bKZzYRxb4b7jXtPaHd1k',
    appId: '1:213904310776:web:a25e3c591721064770960d',
    messagingSenderId: '213904310776',
    projectId: 'mws-kel-8',
    authDomain: 'mws-kel-8.firebaseapp.com',
    storageBucket: 'mws-kel-8.firebasestorage.app',
  );

}